version: '3'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 pingapp.asgi:application
    environment:
      - DJANGO_SETTINGS_MODULE=pingapp.settings
    ports:
      - "8000:8000"
    depends_on:
      - channel
  channel:
    image: redis:5